### ISSUE TITLE
Error installing virtual environment to ubuntu

### ISSUE THREAD

**Issue by ecada** [ecada/Fall2016Swe573_EceAda#21]
$ pip install virtualenvTraceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by ecada** [comment]
I downloaded the python 3.5.2 and write the following:

alias python=python3
