### ISSUE TITLE
Error running "python manage.py migrate" in ubuntu

### ISSUE THREAD

**Issue by ecada** [ecada/Fall2016Swe573_EceAda#24]
Here is the error code -

ImportError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Fall2016Swe573_EceAda/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 36, in <module>
    from sqlite3 import dbapi2 as Database
  File "/usr/local/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

**Comment by ecada** [comment]
I was going to download sqlite3 but all I had to do was **sudo python manage.py migrate**.
